# Parts of configuration file are based on the examples in this repository:
# https://github.com/oneapi-src/oneapi-ci
#
# Which have the following copyright:
# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: MODFLOW 6 distribution (nightly build with Intel)

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
    # - cron: '*/10 * * * *' # run every 10 minutes
    # - cron: '20 */1 * * *' # run every hour at 20 minutes past the hour
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FC: ifort

jobs:
  build_for_os:
    name: build distribution
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            artifact_name: Linux.zip
          - os: macos-latest
            artifact_name: macOS.zip
          - os: windows-latest
            artifact_name: Windows.zip
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9

      - name: Install Python packages
        run: |
          pip install -r requirements.txt
          pip list

      - name: Install ifort
        uses: modflowpy/install-intelfortran-action@v1

      - name: install dos2unix on linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install dos2unix
          dos2unix --version

      - name: Install TeX Live and usgslatex
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra texlive-science texlive-font-utils
          sudo apt install texlive-fonts-extra
          git clone https://github.com/MODFLOW-USGS/usgslatex.git usgslatex
          cd ./usgslatex/usgsLaTeX
          sudo ./install.sh --all-users

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6
          path: modflow6

      - name: Checkout modflow6 examples
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-examples
          path: modflow6-examples

      - name: Update flopy classes
        working-directory: modflow6/autotest
        run: |
          python update_flopy.py

      - name: Create distribution
        if: runner.os != 'Windows'
        run: |
          python make_distribution.py -mf6p ./modflow6 -mf6ep ./modflow6-examples -dp ./${{ runner.os }}

      - name: Create distribution (Windows)
        if: runner.os == 'Windows'
        run: |
          export PATH="/C/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64":$PATH
          python make_distribution.py -mf6p ./modflow6 -mf6ep ./modflow6-examples -dp ./${{ runner.os }}

      - name: Create distribution artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ runner.os }}
          path: |
            ./${{ runner.os }}.zip
