name: MODFLOW 6 nightly build

on:
  schedule:
    # - cron: '0 2 * * *' # run at 2 AM UTC
    - cron: '*/10 * * * *' # run every 10 minutes
    # - cron: '20 */1 * * *' # run every hour at 20 minutes past the hour
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Time
      uses: 1466587594/get-current-time@v1.0.0
      id: current-time
      with:
        format: YYYYMMDD
    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      run: echo $TIME $F_TIME
    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.current-time.outputs.formattedTime }}
        name: ${{ steps.current-time.outputs.formattedTime }} nightly build
        allowUpdates: true
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}  
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.3
      with:
        auto-update-conda: true
        miniconda-version: "latest"
    - name: Install and print system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo ln -fs /usr/bin/gfortran-9 /usr/local/bin/gfortran
        gfortran --version
    - name: Install and print system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        gfortran --version
    - name: Install and print system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        gfortran --version
    - name: Clone MODFLOW 6 repo
      run: |
        git clone https://github.com/MODFLOW-USGS/modflow6.git ../modflow6
      shell: bash
    - name: Determine MODFLOW 6 branch
      run: |
        pwd
        cd ../modflow6
        git branch
        cd ../modflow6-nightly-build
        ls ../
    - name: Install python packages
      run: |
        conda info
        conda install pip requests appdirs nose
        # use pip to install numpy and matplotlib because of a windows issue
        pip install numpy
        pip install https://github.com/modflowpy/pymake/zipball/master
    - name: Print python package versions
      run: |
        import sys
        import nose
        import numpy as np
        import pymake
        pymakepth = pymake.__path__[0]
        print("python version:     {}".format(sys.version))
        print("nosetest version:   {}".format(nose.__version__))
        print("numpy version:      {}".format(np.__version__))
        print("pymake version:     {}".format(pymake.__version__))
        print("")
        print("pymake is installed in: {}".format(pymakepth))
      shell: python
    - name: Build and zip applications
      shell: bash
      run: |
        cd ../modflow6
        nosetests -v -w ./autotest build_nightly.py
        cd ../modflow6-nightly-build

