name: MODFLOW 6 nightly build

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
    # - cron: '*/10 * * * *' # run every 10 minutes
    # - cron: '20 */1 * * *' # run every hour at 20 minutes past the hour
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_for_os:
    name: compile on linux, macos, and windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            artifact_name: linux.zip
            body_name: bodyFileLinux
          - os: macos-latest
            artifact_name: mac.zip
            body_name: bodyFileMac
          - os: windows-latest
            artifact_name: win64.zip
            body_name: bodyFileWindows
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout this github repo
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9

      - name: Install python packages
        run: |
          .github/common/install-python-std.sh

      - name: Print python package versions
        run: |
          pip list

      - name: Workaround for windows-2022 v20220626.1 gfortran executable run failures
        if: runner.os == 'Windows'
        run: |
          .github/common/link-gfortranlib5.sh

      - name: Setup symbolic link to gfortran on Linux
        if: runner.os == 'Linux'
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Setup symbolic link to gfortran on macOS
        if: runner.os == 'macOS'
        run: |
          sudo ln -fs /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          sudo ln -fs /usr/local/bin/gcc-11 /usr/local/bin/gcc
          sudo ln -fs /usr/local/bin/g++-11 /usr/local/bin/g++

      - name: Print GNU compiler versions
        shell: bash
        run: |
          gfortran --version
          gcc --version
          g++ --version

      - name: Clone MODFLOW 6 repo
        run: |
          git clone https://github.com/MODFLOW-USGS/modflow6.git modflow6

      - name: Determine MODFLOW 6 branch
        run: |
          pwd
          cd ./modflow6/
          pwd
          git branch
          cd ../
          pwd
          ls ./

      - name: Update flopy MODFLOW 6 classes
        working-directory: modflow6/autotest
        run: |
          python update_flopy.py

      - name: Build and zip applications
        working-directory: modflow6/distribution
        run: |
          python build_nightly.py

      - name: Move the build zip file
        run: |
          ls -l ./modflow6/distribution/*
          mv ./modflow6/distribution/temp_zip/${{ matrix.artifact_name }} ./${{ matrix.artifact_name }}
          ls -l ./

